Controllers/ClassController.cs
using System;
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Collections.Generic;
using SchoolPlanner.Models;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;


namespace SchoolPlanner.Controllers {
    public class ClassController : Controller {
        private readonly ILogger<ClassController> _logger;
        private readonly SchoolPlannerContext _context;

        public ClassController(ILogger<ClassController> logger, SchoolPlannerContext context) {
            _logger = logger;
            _context = context;
        }

        public async Task<IActionResult> Index() {
            Helper helper = new Helper();
            var classes = await _context.Class.OrderBy(c => c.Name).ToListAsync();
            ViewData["classes"] = classes; 
            return View(helper);
        }

        [HttpPost]
        public async Task<IActionResult> Index(Helper helper) {     
            ViewData["classes"] = await _context.Class.OrderBy(c => c.Name).ToListAsync();
            ViewData["all_lessons"] = await _context.Lesson.ToListAsync();
            var chosen_lessons = await _context.Lesson
                       .Where(l => l.Class.Id == helper.ChosenClass)
                       .Include(l => l.Class)
                       .Include(l => l.Subject)
                       .Include(l => l.Classroom)
                       .Include(l => l.Teacher)
                       .ToListAsync();
            ViewData["chosen_lessons"] = chosen_lessons;
            return View(helper);
        }

        public async Task<IActionResult> AddLesson(Helper helper, int chosenClass, int slot) {
            var classroomsOptions = new List<Classroom>();
            var classrooms = await _context.Classroom.ToListAsync();
            var lessons = await _context.Lesson.ToListAsync();
            foreach (Classroom classroom in classrooms) {
                bool classroomAvailable = true;
                foreach (Lesson lesson in lessons) {
                    if (classroom.Number == lesson.Classroom.Number && slot == lesson.Slot) {
                        classroomAvailable = false;
                        break;
                    }
                }
                if (classroomAvailable) {
                    classroomsOptions.Add(classroom);
                }
            }
            var teachersOptions = new List<Teacher>();
            var teachers = await _context.Teacher.ToListAsync();
            foreach (Teacher teacher in teachers) {
                bool teacherAvailable = true;
                foreach (Lesson lesson in lessons) {
                    if (teacher.Surname == lesson.Teacher.Surname && slot == lesson.Slot) {
                        teacherAvailable = false;
                        break;
                    }
                }
                if (teacherAvailable) {
                    teachersOptions.Add(teacher);
                }
            }

            ViewData["classrooms_options"] = classroomsOptions;
            ViewData["teachers_options"] = teachersOptions;
            ViewData["chosen_class"] = chosenClass;
            ViewData["slot"] = slot;
            ViewData["subjects"] = await _context.Subject.ToListAsync();

            return View(helper);
        }

        public async Task<IActionResult> SuccessfulLessonAdding(int chosenClass, int slot) {
            var classrooms = from c in _context.Classroom
                            where c.Id == (int)TempData["classroom"]
                            select c;
            var classroom = await classrooms.SingleOrDefaultAsync();
            var subjects = from s in _context.Subject
                            where s.Id == (int)TempData["subject"]
                            select s;
            var subject = await subjects.SingleOrDefaultAsync();
            var teachers = from t in _context.Teacher
                            where t.Id == (int)TempData["teacher"]
                            select t;
            var teacher = await teachers.SingleOrDefaultAsync();
            var classes = from c in _context.Class
                            where c.Id == chosenClass
                            select c;
            var _class = await classes.SingleOrDefaultAsync();

            if (classroom == null || subject == null || teacher == null || _class == null) {
                return RedirectToAction("ConcurrencyError", new { errorMessage = "The value you tried to select had been deleted by another user before." });
            }

            _context.Add(new Lesson {
                Classroom = classroom,
                Class = _class,
                Subject = subject,
                Slot = slot,
                Teacher = teacher,
            });
            await _context.SaveChangesAsync();
            return View();     
        }

        public IActionResult UnsuccessfulLessonAdding(int chosenClass, int slot) {
            ViewData["chosen_class"] = chosenClass;
            ViewData["slot"] = slot;
            return View();
        }

        public async Task<IActionResult> EditLesson(Helper helper, int id, int slot) {
            var classroomsOptions = new List<Classroom>();
            var classrooms = await _context.Classroom.ToListAsync();
            var lessons = await _context.Lesson.ToListAsync();
            var chosenLessons = from l in _context.Lesson
                        where l.Id == id
                        select l;
            var chosenLesson = await chosenLessons.SingleOrDefaultAsync();
            if (chosenLesson == null) {
                return RedirectToAction("ConcurrencyError", new { errorMessage = "The lesson you tried to modify had been deleted by another user before." });
            }
            classroomsOptions.Add(chosenLesson.Classroom);
            foreach (Classroom classroom in classrooms) {
                bool classroomAvailable = true;
                foreach (Lesson lesson in lessons) {
                    if (classroom.Number == lesson.Classroom.Number && chosenLesson.Slot == lesson.Slot) {
                        classroomAvailable = false;
                        break;
                    }
                }
                if (classroomAvailable) {
                    classroomsOptions.Add(classroom);
                }
            }
            var teachersOptions = new List<Teacher>();
            var teachers = await _context.Teacher.ToListAsync();
            teachersOptions.Add(chosenLesson.Teacher);
            foreach (Teacher teacher in teachers) {
                bool teacherAvailable = true;
                foreach (Lesson lesson in lessons) {
                    if (teacher.Surname == lesson.Teacher.Surname && chosenLesson.Slot == lesson.Slot) {
                        teacherAvailable = false;
                        break;
                    }
                }
                if (teacherAvailable) {
                    teachersOptions.Add(teacher);
                }
            }

            ViewData["lesson_to_edit_id"] = id;
            ViewData["lesson_timestamp"] = chosenLesson.Timestamp;
            ViewData["classrooms_options"] = classroomsOptions;
            ViewData["teachers_options"] = teachersOptions;
            ViewData["slot"] = slot;
            ViewData["subjects"] = await _context.Subject.ToListAsync();
            ViewData["selected_classroom"] = chosenLesson.Classroom.Id;
            ViewData["selected_subject"] = chosenLesson.Subject.Id;
            ViewData["selected_teacher"] = chosenLesson.Teacher.Id; 

            return View(helper);
        }

        public async Task<IActionResult> SuccessfulLessonEdit(int id, DateTime currentTimestamp) {
            var classrooms = from c in _context.Classroom
                            where c.Id == (int)TempData["classroom"]
                            select c;
            var classroom = await classrooms.SingleOrDefaultAsync();
            var subjects = from s in _context.Subject
                            where s.Id == (int)TempData["subject"]
                            select s;
            var subject = await subjects.SingleOrDefaultAsync();
            var teachers = from t in _context.Teacher
                            where t.Id == (int)TempData["teacher"]
                            select t;
            var teacher = await teachers.SingleOrDefaultAsync();
            
            var lessons = from l in _context.Lesson
                        where l.Id == id
                        select l;
            var lesson = await lessons.SingleOrDefaultAsync();

            if (lesson == null) {
                return RedirectToAction("ConcurrencyError", new { errorMessage = "The lesson you tried to modify had been deleted by another user before." });
            }

            if (classroom == null || subject == null || teacher == null) {
                return RedirectToAction("ConcurrencyError", new { errorMessage = "The value you tried to select had been deleted by another user before." });
            }
            
            try {
                lesson.Classroom = classroom;
                lesson.Subject = subject;
                lesson.Teacher = teacher;
                _context.Entry(lesson).Property("Timestamp").OriginalValue = currentTimestamp;
                _context.Lesson.Update(lesson);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException) {
                return RedirectToAction("ConcurrencyError", new { errorMessage = "The lesson you attempted to edit was modified by another user after you got the original value." });
            }

            return View();
        }

        public IActionResult UnsuccessfulLessonEdit(int id) {
            ViewData["id"] = id;
            return View();
        }

        public async Task<IActionResult> DeleteLesson(int id, DateTime currentTimestamp) {

Views/Class/AddLesson.cshtml
@model Helper

@{
    ViewData["Title"] = "Add a lesson";
}

<div class="text-center">
    <h1 class="display-4">Add a lesson</h1>
</div>

@{ var classroomsOptions = ViewData["classrooms_options"] as List<Classroom>;
    var subjects = ViewData["subjects"] as List<Subject>;
    var teachersOptions = ViewData["teachers_options"] as List<Teacher>; }

@using (Html.BeginForm("ValidateAddedData", "Class", new { chosenClass = ViewData["chosen_class"], slot = ViewData["slot"] })) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger"} )

    <button type="button" class="btn btn-secondary" onclick="location.href='@Url.Action("Index", "Class" )'">Cancel</button><br><br>

    <strong>@Html.LabelFor(model=>model.NewLesson.Classroom, "Classroom")</strong><br>
    @Html.DropDownListFor(model=>model.NewLesson.Classroom, new SelectList(classroomsOptions, "Id", "Number"), "Select the classroom", new {htmlAttributes = new {@class="form-control"}})<br><br>
    <strong>@Html.LabelFor(model=>model.NewLesson.Subject, "Subject")</strong><br>
    @Html.DropDownListFor(model=>model.NewLesson.Subject, new SelectList(subjects, "Id", "Name"), "Select the subject", new {htmlAttributes = new {@class="form-control"}})<br><br>
    <strong>@Html.LabelFor(model=>model.NewLesson.Teacher, "Teacher")</strong><br>
    @Html.DropDownListFor(model=>model.NewLesson.Teacher, new SelectList(teachersOptions, "Id", "Surname"), "Select the teacher", new {htmlAttributes = new {@class="form-control"}})<br><br>

    <button type="submit" class="btn btn-primary">Add</button>
}

Views/Class/ConcurrencyError.cshtml
@{
    ViewData["Title"] = "Concurrency error";
    string error_message = (string)ViewData["error_message"];
    Console.WriteLine((string)ViewData["error_message"]);
    Console.WriteLine(error_message);
}

<div class="text-center">
    <div class="alert alert-danger">
        <strong>Error!</strong> @error_message
    </div>
    <button type="button" class="btn btn-secondary" onclick="location.href='@Url.Action("Index", "Class")'">Return</button><br><br> 
</div>

Views/Class/EditLesson.cshtml
@model Helper

@{
    ViewData["Title"] = "Edit the lesson";
}

<div class="text-center">
    <h1 class="display-4">Edit the lesson</h1>
</div>

@{ int lessonToEditId = (int)ViewData["lesson_to_edit_id"]; 
    var classroomsOptions = ViewData["classrooms_options"] as List<Classroom>;
    var subjects = ViewData["subjects"] as List<Subject>;
    var teachersOptions = ViewData["teachers_options"] as List<Teacher>; 
    var selectedClassroom = (int)ViewData["selected_classroom"];
    var selectedSubject = (int)ViewData["selected_subject"];
    var selectedTeacher = (int)ViewData["selected_teacher"]; }

@using (Html.BeginForm("ValidateEditedData", "Class", new { id = lessonToEditId, currentTimestamp = (DateTime)ViewData["lesson_timestamp"] } )) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger"} )

    <button type="button" class="btn btn-secondary" onclick="location.href='@Url.Action("Index", "Class" )'">Cancel</button><br><br>

    <strong>@Html.LabelFor(model=>model.EditedLesson.Classroom, "Classroom")</strong><br>
    @Html.DropDownListFor(model=>model.EditedLesson.Classroom, new SelectList(classroomsOptions, "Id", "Number", selectedClassroom), "Select the classroom", new {htmlAttributes = new {@class="form-control"}})<br><br>
    <strong>@Html.LabelFor(model=>model.EditedLesson.Subject, "Subject")</strong><br>
    @Html.DropDownListFor(model=>model.EditedLesson.Subject, new SelectList(subjects, "Id", "Name", selectedSubject), "Select the subject", new {htmlAttributes = new {@class="form-control"}})<br><br>
    <strong>@Html.LabelFor(model=>model.EditedLesson.Teacher, "Teacher")</strong><br>
    @Html.DropDownListFor(model=>model.EditedLesson.Teacher, new SelectList(teachersOptions, "Id", "Surname", selectedTeacher), "Select the teacher", new {htmlAttributes = new {@class="form-control"}})<br><br>

    <button type="submit" class="btn btn-primary">Edit</button>
    <button type="button" class="btn btn-danger" onclick="location.href='@Url.Action("DeleteLesson", "Class", new { id = lessonToEditId, currentTimestamp = (DateTime)ViewData["lesson_timestamp"] })'">Delete</button>
}

Views/Class/Index.cshtml
@using System.Collections.Generic
@using SchoolPlanner.Models
@model Helper

@{
    ViewData["Title"] = "Classes";
}

<style>
    th {width:150px;}
    button {height:50px; max-width:150px;}
</style>

<div class="text-center">

    <h1 class="display-4">CLASSES</h1>

    @{ var classes = ViewData["classes"] as List<Class>;}

    @* @using (Html.BeginForm("Index", "Class", new { _class = Model.ChosenClass })) { // TODO *@
    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true, "", new { @class = "text-danger"} )
        if (classes != null && classes.Any()) {
            @Html.DropDownListFor(model=>model.ChosenClass, new SelectList(classes, "Id", "Name"), "Select the class", new {htmlAttributes = new {@class="form-control"}})
            <button type="submit" class="btn btn-primary">Select</button>
        }
        else {
            <p>No classes defined</p>
        }
    }

    @{var all_lessons = ViewData["all_lessons"] as List<Lesson>;}
    @{var chosen_lessons = ViewData["chosen_lessons"] as List<Lesson>;}

    @if (Model.ChosenClass != null) {
        <table>
            <thead>
                <th></th>
                <th>Monday</th>
                <th>Tuesday</th>
                <th>Wednesday</th>
                <th>Thursday</th>
                <th>Friday</th>
            </thead>
            @{int slot_number = 0;}
            @for (int i=0; i<9; i++) {
                <tr>
                    @switch(i) {
                        case 0:
                            <td><strong>8:00 - 8:45</strong></td>
                            break;
                        case 1:
                            <td><strong>9:00 - 9:45</strong></td>
                            break;
                        case 2:
                            <td><strong>10:00 - 10:45</strong></td>
                            break;
                        case 3:
                            <td><strong>11:00 - 11:45</strong></td>
                            break;
                        case 4:
                            <td><strong>12:00 - 12:45</strong></td>
                            break;
                        case 5:
                            <td><strong>13:00 - 13:45</strong></td>
                            break;
                        case 6:
                            <td><strong>14:00 - 14:45</strong></td>
                            break;
                        case 7:
                            <td><strong>15:00 - 15:45</strong></td>
                            break;
                        case 8:
                            <td><strong>16:00 - 16:45</strong></td>
                            break;
                        default:
                            break;
                    }
                    @for (int j=0; j<5; ++j) {
                        <td>
                            @{slot_number++;}
                            @{ bool lesson_found = false; }
                            @foreach (Lesson lesson in chosen_lessons) { // TODO: for loop outside this loops (i, j) and adding contents to buttons by their id 
                                int? lessonId = null;
                                if (lesson.Slot == slot_number) {
                                    foreach (var l in all_lessons) {
                                        if (Object.Equals(lesson, l)) {
                                            lessonId = lesson.Id;
                                            break;
                                        }
                                    }
                                    <button type="button" class="btn btn-primary btn-block" onclick="location.href='@Url.Action("EditLesson", "Class", new { id = lessonId, slot = slot_number })'">@lesson.Classroom.Number @lesson.Subject.Name</button> 
                                    lesson_found = true;
                                    break;
                                }   
                            }
                            @if (lesson_found == false) {
                                <button type="button" class="btn btn-primary btn-block" onclick="location.href='@Url.Action("AddLesson", "Class", new { slot = slot_number, chosenClass = Model.ChosenClass })'"></button>  
                            }
                        </td>
                    }
                </tr>   
                <br>
            }
        </table>
    }
</div>