Models/Classroom.cs
using System;
using System.ComponentModel.DataAnnotations;


namespace SchoolPlanner.Models {
    public class Classroom {

        public int Id { get; set; }

        [Required]
        [MaxLength(10)]
        public string Number { get; set; }

        [Timestamp]
        public DateTime Timestamp { get; set; }
    }
}

Controllers/ClassroomController.cs
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SchoolPlanner.Models;
using Microsoft.EntityFrameworkCore;
using System;
using System.Threading.Tasks;


namespace SchoolPlanner.Controllers {
    public class ClassroomController : Controller {
        private readonly ILogger<ClassroomController> _logger;
        private readonly SchoolPlannerContext _context;

        public ClassroomController(ILogger<ClassroomController> logger, SchoolPlannerContext context) {
            _logger = logger;
            _context = context;
        }

        public async Task<IActionResult> Index() {
            Helper helper = new Helper();
            var classrooms = await _context.Classroom.OrderBy(c => c.Number).ToListAsync();
            ViewData["classrooms"] = classrooms; 
            return View(helper);
        }

        [HttpPost]
        public async Task<IActionResult> Index(Helper helper) { 
            ViewData["classrooms"] = await _context.Classroom.OrderBy(c => c.Number).ToListAsync();
            ViewData["all_lessons"] = await _context.Lesson.ToListAsync();
            var chosen_lessons = await _context.Lesson
                       .Where(l => l.Classroom.Id == helper.ChosenClassroom)
                       .Include(l => l.Class)
                       .Include(l => l.Subject)
                       .Include(l => l.Classroom)
                       .Include(l => l.Teacher)
                       .ToListAsync();
            ViewData["chosen_lessons"] = chosen_lessons;
            return View(helper);
        }

        public async Task<IActionResult> AddLesson(Helper helper, int chosenClassroom, int slot) {
            var classesOptions = new List<Class>();
            var classes = await _context.Class.ToListAsync();
            var lessons = await _context.Lesson.ToListAsync();
            foreach (Class _class in classes) {
                bool classAvailable = true;
                foreach (Lesson lesson in lessons) {
                    if (_class.Name == lesson.Class.Name && slot == lesson.Slot) {
                        classAvailable = false;
                        break;
                    }
                }
                if (classAvailable) {
                    classesOptions.Add(_class);
                }
            }
            var teachersOptions = new List<Teacher>();
            var teachers = await _context.Teacher.ToListAsync();
            foreach (Teacher teacher in teachers) {
                bool teacherAvailable = true;
                foreach (Lesson lesson in lessons) {
                    if (teacher.Surname == lesson.Teacher.Surname && slot == lesson.Slot) {
                        teacherAvailable = false;
                        break;
                    }
                }
                if (teacherAvailable) {
                    teachersOptions.Add(teacher);
                }
            }

            ViewData["classes_options"] = classesOptions;
            ViewData["teachers_options"] = teachersOptions;
            ViewData["chosen_classroom"] = chosenClassroom;
            ViewData["slot"] = slot;
            ViewData["subjects"] = await _context.Subject.ToListAsync();

            return View(helper);
        }

        public async Task<IActionResult> SuccessfulLessonAdding(int chosenClassroom, int slot) {
            var classes = from c in _context.Class
                            where c.Id == (int)TempData["class"]
                            select c;
            var _class = await classes.SingleOrDefaultAsync();
            var subjects = from s in _context.Subject
                            where s.Id == (int)TempData["subject"]
                            select s;
            var subject = await subjects.SingleOrDefaultAsync();
            var teachers = from t in _context.Teacher
                            where t.Id == (int)TempData["teacher"]
                            select t;
            var teacher = await teachers.SingleOrDefaultAsync();
            var classrooms = from c in _context.Classroom
                            where c.Id == chosenClassroom
                            select c;
            var classroom = await classrooms.SingleOrDefaultAsync();

            if (_class == null || subject == null || teacher == null || classroom == null) {
                return RedirectToAction("ConcurrencyError", new { errorMessage = "The value you tried to select had been deleted by another user before." });
            }

            _context.Add(new Lesson {
                Classroom = classroom,
                Class = _class,
                Subject = subject,
                Slot = slot,
                Teacher = teacher,
            });
            await _context.SaveChangesAsync();
            return View();     
        }

        public IActionResult UnsuccessfulLessonAdding(int chosenClassroom, int slot) {
            ViewData["chosen_classroom"] = chosenClassroom;
            ViewData["slot"] = slot;
            return View();
        }

        public async Task<IActionResult> EditLesson(Helper helper, int id, int slot) {
            var classesOptions = new List<Class>();
            var classes = await _context.Class.ToListAsync();
            var lessons = await _context.Lesson.ToListAsync();
            var chosenLessons = from l in _context.Lesson
                        where l.Id == id
                        select l;
            var chosenLesson = await chosenLessons.SingleOrDefaultAsync();
            if (chosenLesson == null) {
                return RedirectToAction("ConcurrencyError", new { errorMessage = "The lesson you tried to modify had been deleted by another user before." });
            }
            classesOptions.Add(chosenLesson.Class);
            foreach (Class _class in classes) {
                bool classAvailable = true;
                foreach (Lesson lesson in lessons) {
                    if (_class.Name == lesson.Class.Name && chosenLesson.Slot == lesson.Slot) {
                        classAvailable = false;
                        break;
                    }
                }
                if (classAvailable) {
                    classesOptions.Add(_class);
                }
            }
            var teachersOptions = new List<Teacher>();
            var teachers = await _context.Teacher.ToListAsync();
            teachersOptions.Add(chosenLesson.Teacher);
            foreach (Teacher teacher in teachers) {
                bool teacherAvailable = true;
                foreach (Lesson lesson in lessons) {
                    if (teacher.Surname == lesson.Teacher.Surname && chosenLesson.Slot == lesson.Slot) {
                        teacherAvailable = false;
                        break;
                    }
                }
                if (teacherAvailable) {
                    teachersOptions.Add(teacher);
                }
            }

            ViewData["lesson_to_edit_id"] = id;
            ViewData["lesson_timestamp"] = chosenLesson.Timestamp;
            ViewData["classes_options"] = classesOptions;
            ViewData["teachers_options"] = teachersOptions;
            ViewData["slot"] = slot;
            ViewData["subjects"] = await _context.Subject.ToListAsync();
            ViewData["selected_class"] = chosenLesson.Class.Id;
            ViewData["selected_subject"] = chosenLesson.Subject.Id;
            ViewData["selected_teacher"] = chosenLesson.Teacher.Id; 

            return View(helper);
        }

        public async Task<IActionResult> SuccessfulLessonEdit(int id, DateTime currentTimestamp) {
            var classes = from c in _context.Class
                            where c.Id == (int)TempData["class"]
                            select c;
            var _class = await classes.SingleOrDefaultAsync();
            var subjects = from s in _context.Subject
                            where s.Id == (int)TempData["subject"]
                            select s;
            var subject = await subjects.SingleOrDefaultAsync();
            var teachers = from t in _context.Teacher
                            where t.Id == (int)TempData["teacher"]
                            select t;
            var teacher = await teachers.SingleOrDefaultAsync();
            
            var lessons = from l in _context.Lesson
                        where l.Id == id
                        select l;
            var lesson = await lessons.SingleOrDefaultAsync();

            if (lesson == null) {
                return RedirectToAction("ConcurrencyError", new { errorMessage = "The lesson you tried to modify had been deleted by another user before." });
            }

            if (_class == null || subject == null || teacher == null) {
                return RedirectToAction("ConcurrencyError", new { errorMessage = "The value you tried to select had been deleted by another user before." });
            }

            try {
                lesson.Class = _class;
                lesson.Subject = subject;
                lesson.Teacher = teacher;
                _context.Entry(lesson).Property("Timestamp").OriginalValue = currentTimestamp;
                _context.Lesson.Update(lesson);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException) {
                return RedirectToAction("ConcurrencyError", new { errorMessage = "The lesson you attempted to edit was modified by another user after you got the original value." });
            }

            return View();
        }

        public IActionResult UnsuccessfulLessonEdit(int id) {
            ViewData["id"] = id;
            return View();
        }

        public async Task<IActionResult> DeleteLesson(int id, DateTime currentTimestamp) {
            var lessons = from l in _context.Lesson
                            where l.Id == id

Views/Classroom/AddLesson.cshtml
@model Helper

@{
    ViewData["Title"] = "Add a lesson";
}

<div class="text-center">
    <h1 class="display-4">Add a lesson</h1>
</div>

@{ var classesOptions = ViewData["classes_options"] as List<Class>;
    var subjects = ViewData["subjects"] as List<Subject>;
    var teachersOptions = ViewData["teachers_options"] as List<Teacher>; }

@using (Html.BeginForm("ValidateAddedData", "Classroom", new { chosenClassroom = ViewData["chosen_classroom"], slot = ViewData["slot"] })) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger"} )

    <button type="button" class="btn btn-secondary" onclick="location.href='@Url.Action("Index", "Classroom" )'">Cancel</button><br><br>

    <strong>@Html.LabelFor(model=>model.NewLesson.Class, "Class")</strong><br>
    @Html.DropDownListFor(model=>model.NewLesson.Class, new SelectList(classesOptions, "Id", "Name"), "Select the class", new {htmlAttributes = new {@class="form-control"}})<br><br>
    <strong>@Html.LabelFor(model=>model.NewLesson.Subject, "Subject")</strong><br>
    @Html.DropDownListFor(model=>model.NewLesson.Subject, new SelectList(subjects, "Id", "Name"), "Select the subject", new {htmlAttributes = new {@class="form-control"}})<br><br>
    <strong>@Html.LabelFor(model=>model.NewLesson.Teacher, "Teacher")</strong><br>
    @Html.DropDownListFor(model=>model.NewLesson.Teacher, new SelectList(teachersOptions, "Id", "Surname"), "Select the teacher", new {htmlAttributes = new {@class="form-control"}})<br><br>

    <button type="submit" class="btn btn-primary">Add</button>
}

Views/Classroom/ConcurrencyError.cshtml
@{
    ViewData["Title"] = "Concurrency error";
    string error_message = (string)ViewData["error_message"];
    Console.WriteLine((string)ViewData["error_message"]);
    Console.WriteLine(error_message);
}

<div class="text-center">
    <div class="alert alert-danger">
        <strong>Error!</strong> @error_message
    </div>
    <button type="button" class="btn btn-secondary" onclick="location.href='@Url.Action("Index", "Classroom")'">Return</button><br><br> 
</div>

Views/Classroom/ConcurrencyUnsuccessfulEdition.cshtml
@{
    ViewData["Title"] = "Concurrency error";
}

<div class="text-center">
    <div class="alert alert-danger">
        <strong>Error!</strong> The value you tried to modify or add had been modified or deleted by another user before.
    </div>
    <button type="button" class="btn btn-secondary" onclick="location.href='@Url.Action("Index", "Classroom")'">Return</button><br><br> 
</div>

Views/Classroom/EditLesson.cshtml
@using System;
@model Helper

@{
    ViewData["Title"] = "Edit the lesson";
}

<div class="text-center">
    <h1 class="display-4">Edit the lesson</h1>
</div>

@{ int lessonToEditId = (int)ViewData["lesson_to_edit_id"]; 
    var classesOptions = ViewData["classes_options"] as List<Class>;
    var subjects = ViewData["subjects"] as List<Subject>;
    var teachersOptions = ViewData["teachers_options"] as List<Teacher>; 
    var selectedClass = (int)ViewData["selected_class"];
    var selectedSubject = (int)ViewData["selected_subject"];
    var selectedTeacher = (int)ViewData["selected_teacher"]; }

@using (Html.BeginForm("ValidateEditedData", "Classroom", new { id = lessonToEditId, currentTimestamp = (DateTime)ViewData["lesson_timestamp"] } )) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger"} )

    <button type="button" class="btn btn-secondary" onclick="location.href='@Url.Action("Index", "Classroom" )'">Cancel</button><br><br>

    <strong>@Html.LabelFor(model=>model.EditedLesson.Class, "Class")</strong><br>
    @Html.DropDownListFor(model=>model.EditedLesson.Class, new SelectList(classesOptions, "Id", "Name", selectedClass), "Select the class", new {htmlAttributes = new {@class="form-control"}})<br><br>
    <strong>@Html.LabelFor(model=>model.EditedLesson.Subject, "Subject")</strong><br>
    @Html.DropDownListFor(model=>model.EditedLesson.Subject, new SelectList(subjects, "Id", "Name", selectedSubject), "Select the subject", new {htmlAttributes = new {@class="form-control"}})<br><br>
    <strong>@Html.LabelFor(model=>model.EditedLesson.Teacher, "Teacher")</strong><br>
    @Html.DropDownListFor(model=>model.EditedLesson.Teacher, new SelectList(teachersOptions, "Id", "Surname", selectedTeacher), "Select the teacher", new {htmlAttributes = new {@class="form-control"}})<br><br>

    <button type="submit" class="btn btn-primary">Edit</button>
    <button type="button" class="btn btn-danger" onclick="location.href='@Url.Action("DeleteLesson", "Classroom", new { id = lessonToEditId, currentTimestamp = (DateTime)ViewData["lesson_timestamp"] })'">Delete</button>
}

Views/Classroom/Index.cshtml
@using System.Collections.Generic
@using SchoolPlanner.Models
@using System;
@model Helper

@{
    ViewData["Title"] = "Classrooms";
}

<style>
    th {width:150px;}
    button {height:50px; max-width:150px;}
</style>

<div class="text-center">

    <h1 class="display-4">CLASSROOMS</h1>

    @{ var classrooms = ViewData["classrooms"] as List<Classroom>;}

    @* @using (Html.BeginForm("Index", "Class", new { _class = Model.ChosenClassroom })) { // TODO *@
    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true, "", new { @class = "text-danger"} )
        if (classrooms != null && classrooms.Any()) {
            @Html.DropDownListFor(model=>model.ChosenClassroom, new SelectList(classrooms, "Id", "Number"), "Select the classroom", new {htmlAttributes = new {@class="form-control"}})
            <button type="submit" class="btn btn-primary">Select</button>
        }
        else {
            <p>No classrooms defined</p>
        }
    }

    @{var all_lessons = ViewData["all_lessons"] as List<Lesson>;}
    @{var chosen_lessons = ViewData["chosen_lessons"] as List<Lesson>;}

    @if (Model.ChosenClassroom != null) {
        <table>
            <thead>
                <th></th>
                <th>Monday</th>
                <th>Tuesday</th>
                <th>Wednesday</th>
                <th>Thursday</th>
                <th>Friday</th>
            </thead>
            @{int slot_number = 0;}
            @for (int i=0; i<9; i++) {
                <tr>
                    @switch(i) {
                        case 0:
                            <td><strong>8:00 - 8:45</strong></td>
                            break;
                        case 1:
                            <td><strong>9:00 - 9:45</strong></td>
                            break;
                        case 2:
                            <td><strong>10:00 - 10:45</strong></td>
                            break;
                        case 3:
                            <td><strong>11:00 - 11:45</strong></td>
                            break;
                        case 4:
                            <td><strong>12:00 - 12:45</strong></td>
                            break;
                        case 5:
                            <td><strong>13:00 - 13:45</strong></td>
                            break;
                        case 6:
                            <td><strong>14:00 - 14:45</strong></td>
                            break;
                        case 7:
                            <td><strong>15:00 - 15:45</strong></td>
                            break;
                        case 8:
                            <td><strong>16:00 - 16:45</strong></td>
                            break;
                        default:
                            break;
                    }
                    @for (int j=0; j<5; ++j) {
                        <td>
                            @{slot_number++;}
                            @{ bool lesson_found = false; }
                            @{ if (chosen_lessons != null && chosen_lessons.Any()) {
                                foreach (Lesson lesson in chosen_lessons) { // TODO: for loop outside this loops (i, j) and adding contents to buttons by their id 
                                    int? lessonId = null;
                                    if (lesson.Slot == slot_number) {
                                        foreach (var l in all_lessons) {
                                            if (Object.Equals(lesson, l)) {
                                                lessonId = lesson.Id;
                                                break;
                                            }
                                        }
                                        <button type="button" class="btn btn-primary btn-block" onclick="location.href='@Url.Action("EditLesson", "Classroom", new { id = lessonId, slot = slot_number })'">@lesson.Class.Name</button> 
                                        lesson_found = true;
                                        break;
                                    }   
                                }
                            }}    
                            @if (lesson_found == false) {
                                <button type="button" class="btn btn-primary btn-block" onclick="location.href='@Url.Action("AddLesson", "Classroom", new { slot = slot_number, chosenClassroom = Model.ChosenClassroom })'"></button>  
                            }
                        </td>
                    }
                </tr>   
                <br>
            }
        </table>
    }
</div>

Views/Classroom/SuccessfulLessonAdding.cshtml
@{
    ViewData["Title"] = "Lesson added";
}

<div class="text-center">
    <div class="alert alert-success">
        <strong>Success!</strong> Lesson successfully added.
    </div>
    <button type="button" class="btn btn-secondary" onclick="location.href='@Url.Action("Index", "Classroom" )'">OK</button><br><br> 
</div>

Views/Classroom/SuccessfulLessonEdit.cshtml
@{
    ViewData["Title"] = "Lesson edited";
}

<div class="text-center">
    <div class="alert alert-success">
        <strong>Success!</strong> Lesson successfully edited.
    </div>
    <button type="button" class="btn btn-secondary" onclick="location.href='@Url.Action("Index", "Classroom" )'">OK</button><br><br>
</div>

Views/Classroom/UnsuccessfulLessonAdding.cshtml
@{
    ViewData["Title"] = "Error";
}

<div class="text-center">
    <div class="alert alert-danger">
        <strong>Error!</strong> You did not select all values.
    </div>
    <button type="button" class="btn btn-secondary" onclick="location.href='@Url.Action("AddLesson", "Classroom", new { chosenClassroom = ViewData["chosen_classroom"], slot = ViewData["slot"] })'">Return</button><br><br>
</div>

Views/Classroom/UnsuccessfulLessonEdit.cshtml
@{
    ViewData["Title"] = "Error";
}

<div class="text-center">
    <div class="alert alert-danger">
        <strong>Error!</strong> You did not select all values.
    </div>
    <button type="button" class="btn btn-secondary" onclick="location.href='@Url.Action("EditLesson", "Classroom", new { id = ViewData["id"] } )'">Return</button><br><br> 
</div>